name: app_dev
description: A new Flutter project.

# Remove the line below if you want to publish to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  provider: ^6.0.5
  battery_plus: ^6.0.1
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.0.15 # Added for theme persistence

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
